name: Deploy Bulning Development Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Remove legacy build files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ssh_server }}
          username: ${{ secrets.ssh_user }}
          key: ${{ secrets.ssh_key }}
          script: |
            rm -rf ~/${{ secrets.serverdir }}/dist

      - name: Upload build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ssh_server }}
          username: ${{ secrets.ssh_user }}
          key: ${{ secrets.ssh_key }}
          source: "dist/*"
          target: "~/${{ secrets.serverdir }}"
      - name: Setup Server and start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ssh_server }}
          username: ${{ secrets.ssh_user }}
          key: ${{ secrets.ssh_key }}
          script: |
            cd ~/${{ secrets.serverdir }}
            git pull origin ${{ github.ref_name }}
            npm install
            sudo npx pm2 start 'npm run start'
